//Effect Node is a type of node that processes a signal through a VST plugin

#include "Node.h"

#include <vector>
#include <string>
#include "stdafx.h"
#include "InputSignal.h"
#include "ModWire.h"
#include "MidiWire.h"
#include "ParamMap.h"
#include "aeffect.h"

class EffectNode : public Node
{
public:
	std::vector<InputSignal> inputs; //List of input connections
	std::string pluginName; //File name of plugin DLL
	AEffect plugin; //Instance of effect plugin (Class defined in VST SDK)
	double **inputBuffer; //Array of input signal buffers
	double **outputBuffer; //Array of output signal buffers
	std::vector<ModWire> modWires; //Mod wire carries modulation signal from a signal source to a parameter in the plugin
	std::vector<MidiWire> midiWires; //MIDI wire carries midi data from a MIDI generating node to instrument plugin
	std::vector<VstMidiEvent> inEvents; //MIDI events received by this node
	std::vector<VstMidiEvent> outEvents; //MIDI events generated by this node
	std::vector<ParamMap> modValues; //Mapping of modulation sources to parameters
	EffectNode(std::string id); //Constructor (parameter is node ID)
	void processEffect(); //Process signal through plugin
};
\ No newline at end of file
